### ISSUE TITLE
Issue when user rejects the signing requests for "Get Friends" and "Chat with Friends".

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#32]
Issue when user rejects the signing requests for "Get Friends" and "Chat with Friends".

Steps:
1. Visit TSViewer and click on Pepe token.
2. Click on Get Friends button and reject the request.
3. Observe the UI.
4. Click on Chat with Friends button and reject the request.
5. Observe the UI.

Issues:
1. When user rejects the first request, a second signing request is sent: Should we be re-sending the signing request after user rejects it once?
2. Error shown when user rejects the signing request for "Get Friends" the error message is shown on the UI in the dialog box - But it disappears too quickly.
3. Error shown when user rejects the signing request for "Chat with Friends" the error message is shown as an alert pop-up - Should the message be shown like how it is shown for Get Friends on the UI instead of an alert pop-up?

Recording:

https://github.com/user-attachments/assets/53737a18-b07c-433f-973a-3f76e42aa861

**Comment by nicktaras** [comment]
Yep, good point the error handling should be consistent. I'll move this error to the Card UI.

**Comment by nicktaras** [comment]
Address these points:

1. Added logic to stop MetaMask if the user rejects the first request
2. Updated the error timer
3. Moved the errors into the UI view. Updated the error messages to include that the cause of error could be due to rejection to sign from the user.

Additional fix: Updated the error UI component to be fixed, to follow the user should they scroll up/down they will still see the error. 

I'll push these changes ready for the next version.

**Comment by nicktaras** [comment]
Fix added to PEPE branch version.

**Comment by abhishes007** [comment]
Fixed and verified, user is shown the appropriated reject message for rejected signing request:

Uploading chrome_cZI07HyGa0.mp4…
